scan_timeout = 30
command_timeout = 500

format = """$os$directory$character"""
right_format = """$all"""

add_newline = true

[os]
disabled = false
format = "[$symbol]($style) "
style = "bold white"

[os.symbols]
Macos = "󰀵 "

[directory]
truncation_length = 1
style = 'bold cyan'
format = '[$path]($style)[$read_only]($read_only_style) '

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✘](bold red) '

[git_branch]
symbol = ' '
style = 'bold purple'
format = '[$symbol$branch]($style) '

[git_status]
style = 'bold red'
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = '='
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
up_to_date = ''
untracked = '?'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'

[cmd_duration]
min_time = 3000
format = 'took [$duration]($style) '
style = 'dimmed yellow'

[nodejs]
symbol = '󰎙 '
format = 'via [$symbol($version )]($style)'
style = 'bold green'
detect_files = []
detect_folders = ['node_modules']

[bun]
symbol = '󰮯 '
format = 'via [$symbol($version )]($style)'
style = 'bold 201'

[python]
symbol = '󰌠 '
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = 'bold yellow'

[rust]
symbol = '󱘗 '
format = 'via [$symbol($version )]($style)'
style = 'bold orange'

[golang]
symbol = ' '
format = 'via [$symbol($version )]($style)'
style = 'bold cyan'

[java]
symbol = '󰬷 '
format = 'via [$symbol($version )]($style)'
style = 'bold red'

[package]
symbol = '󰏗 '
format = 'is [$symbol$version]($style) '
style = 'bold 208'

[docker_context]
symbol = ' '
format = '[$symbol$context]($style) '
style = 'bold blue'
only_with_files = true

[terraform]
symbol = '󱁢 '
format = 'via [$symbol$workspace]($style) '
style = 'bold 105'

[kubernetes]
symbol = '󱃾 '
format = 'at [$symbol$context( \($namespace\))]($style) '
style = 'cyan'
disabled = false
detect_files = ['k8s', '.kube']

[aws]
symbol = ' '
format = 'on [$symbol$profile]($style) '
style = 'bold yellow'
force_display = false

[gcloud]
symbol = ' '
format = 'on [$symbol$project]($style) '
style = 'bold blue'

[status]
disabled = false
format = '[$symbol $exit_code]($style) '
symbol = '󰅙 '
style = 'bold red'
